apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjM05qWXhNVGc1T1N3aWFXRjBJam94TnpjMk5qRXhPRGs1ZlEud0dGcXkwZFBpa2xRR2xsZDBXbTNka2ZkNjN5N3ZPaFVVYUhHU2Y4bEN5QQ==

